[project]
name = "finance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.15.0",
    "phidata>=2.7.9",
    "python-dotenv>=1.0.1",
    "yfinance>=0.2.52",
]
